/* VENGRATH — Sala Chwały: renderer backed by data/*.json */
const labels={alive:"ŻYJE / LOS OTWARTY",dead:"POLEGŁA / POLEGŁY",finished:"HISTORIA ZAKOŃCZONA",unknown:"LOS NIEUSTALONY",abandoned:"KAMPANIA PORZUCONA"};
const norm=s=>String(s??"").toLocaleLowerCase("pl-PL").normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const load=async name=>{const r=await fetch("/data/"+name+".json",{cache:"no-cache"});if(!r.ok)throw new Error("Nie udało się wczytać "+name);return r.json()};
const $=id=>document.getElementById(id);
let characters=[],players=[],campaigns=[],assets=[],assetMap=new Map(),playerMap=new Map(),campaignMap=new Map();
const filters={campaign:$("campaignFilter"),class:$("classFilter"),race:$("raceFilter"),fate:$("fateFilter"),player:$("playerFilter")};
function tags(c){return {campaign:c.campaignIds.map(id=>campaignMap.get(id)?.name).filter(Boolean),class:c.classes||["Placeholder"],race:[c.race||"Placeholder"],fate:[c.fate||"unknown"],player:[playerMap.get(c.playerId)?.name||"Nie podano"]}}
function allTags(type){return [...new Set(characters.flatMap(c=>tags(c)[type]||[]))].filter(Boolean).sort((a,b)=>a.localeCompare(b,"pl"))}
function populate(select,type,label){select.innerHTML="<option value=\"\">"+label+"</option>";for(const x of allTags(type)){const o=document.createElement("option");o.value=x;o.textContent=x;select.append(o)}}
function tagMarkup(type,values){return values.map(x=>'<span class="tag tag-'+type+'">'+escapeHtml(x)+'</span>').join("")}
function record(c){return {...c,tags:tags(c),portrait:assetMap.get(c.portraitId)?.path||""}}
function matches(r){const q=norm($("search").value.trim());if(q){const hay=[r.name,r.description,...Object.values(r.tags).flat()].join(" ");if(!norm(hay).includes(q))return false}for(const [type,el] of Object.entries(filters))if(el.value&&!r.tags[type].includes(el.value))return false;return true}
function openCharacter(r){const m=$("characterModal"),f=r.tags.fate[0]||"unknown";$("modalContent").innerHTML='<div class="modal-left"><img class="modal-portrait" src="'+escapeHtml(r.portrait)+'" alt="'+escapeHtml(r.name)+'"><div class="modal-identity"><span class="modal-kicker">REKORD POSTACI</span><h2 id="modalCharacterName">'+escapeHtml(r.name)+'</h2><div class="modal-meta"><div class="modal-meta-row"><b>Tagi kampanii</b><span class="modal-tags">'+tagMarkup("campaign",r.tags.campaign)+'</span></div><div class="modal-meta-row"><b>Tagi klasy</b><span class="modal-tags">'+tagMarkup("class",r.tags.class)+'</span></div><div class="modal-meta-row"><b>Tagi rasy</b><span class="modal-tags">'+tagMarkup("race",r.tags.race)+'</span></div><div class="modal-meta-row"><b>Tagi losu</b><span class="modal-tags">'+tagMarkup("fate",r.tags.fate)+'</span></div><div class="modal-meta-row"><b>Tagi gracza</b><span class="modal-tags">'+tagMarkup("player",r.tags.player)+'</span></div></div></div></div><div class="modal-right"><span class="modal-right-kicker">ARCHIWUM / NOTATKA</span><h3>Backstory</h3><div class="modal-note empty-note">'+escapeHtml("Nie ma nic więcej do dodania")+'</div><div class="modal-fate"><strong>'+escapeHtml(labels[f]||"")+'</strong><br>'+escapeHtml(r.description||"")+'</div></div>';m.hidden=false;m.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeCharacter(){const m=$("characterModal");m.hidden=true;m.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
function render(){const rows=characters.map(record).filter(matches);$("resultCount").textContent=rows.length+" / "+characters.length;$("hallGrid").innerHTML=rows.map(r=>'<article class="card" data-id="'+r.id+'" data-fate="'+escapeHtml(r.fate)+'" tabindex="0" role="button" aria-label="Otwórz kartę postaci '+escapeHtml(r.name)+'"><div class="portrait"><img src="'+escapeHtml(r.portrait)+'" alt="'+escapeHtml(r.name)+'" loading="lazy" onerror="this.remove()"></div><div class="card-body"><h3>'+escapeHtml(r.name)+'</h3><div class="meta"><div><b>Tagi kampanii</b><span class="tags">'+tagMarkup("campaign",r.tags.campaign)+'</span></div><div><b>Tagi klasy</b><span class="tags">'+tagMarkup("class",r.tags.class)+'</span></div><div><b>Tagi rasy</b><span class="tags">'+tagMarkup("race",r.tags.race)+'</span></div><div><b>Tagi losu</b><span class="tags">'+tagMarkup("fate",r.tags.fate)+'</span></div><div><b>Tagi gracza</b><span class="tags">'+tagMarkup("player",r.tags.player)+'</span></div></div><div class="fate"><strong>'+escapeHtml(labels[r.fate]||"")+'</strong><br>'+escapeHtml(r.description)+'</div></div></article>').join("");$("empty").hidden=rows.length!==0;document.querySelectorAll(".card").forEach(el=>{const c=characters.find(x=>x.id===el.dataset.id);el.onclick=()=>openCharacter(record(c));el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openCharacter(record(c))}}})}
(async()=>{const [c,p,ca,a]=await Promise.all([load("characters"),load("players"),load("campaigns"),load("assets")]);characters=c.characters;players=p.players;campaigns=ca.campaigns;assets=a.assets;playerMap=new Map(players.map(x=>[x.id,x]));campaignMap=new Map(campaigns.map(x=>[x.id,x]));assetMap=new Map(assets.map(x=>[x.id,x]));populate(filters.campaign,"campaign","Wszystkie kampanie");populate(filters.class,"class","Wszystkie klasy");populate(filters.race,"race","Wszystkie rasy");populate(filters.fate,"fate","Wszystkie losy");populate(filters.player,"player","Wszyscy gracze");$("countAll").textContent=characters.length;$("countDead").textContent=characters.filter(x=>x.fate==="dead").length;$("countCampaigns").textContent=campaigns.length;$("countPlayers").textContent=players.filter(x=>x.name!=="NPC"&&x.name!=="Nie podano").length;render();[$("search"),...Object.values(filters)].forEach(x=>x.addEventListener("input",render));$("clearFilters").onclick=()=>{$("search").value="";Object.values(filters).forEach(x=>x.value="");render()};$("modalClose").onclick=closeCharacter;$("characterModal").onclick=e=>{if(e.target.matches("[data-modal-close]"))closeCharacter()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("characterModal").hidden)closeCharacter()})})().catch(e=>{console.error(e);$("hallGrid").innerHTML='<div class="empty">NIE UDAŁO SIĘ WCZYTAĆ ARCHIWUM</div>'});
