const menuToggle=document.querySelector('.menu-toggle'),siteNav=document.querySelector('.site-nav'),header=document.querySelector('.site-header');
if(menuToggle&&siteNav)menuToggle.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.textContent=open?'CLOSE':'MENU';});
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>20),{passive:true});
const currentPath=location.pathname.replace(/\\/g,'/');
document.querySelectorAll('.site-nav a').forEach(link=>{const target=new URL(link.href,location.href).pathname.replace(/\\/g,'/');if(target!=='/'&&currentPath.startsWith(target))link.setAttribute('aria-current','page');});
cleanInterface();
addSkipLink();addSearchTrigger();addMetadata();
function cleanInterface(){
 const wordmark=document.querySelector('.wordmark');
 if(wordmark){wordmark.textContent='VengrathDM';}
 document.querySelectorAll('.site-nav a').forEach(link=>{link.textContent=link.textContent.replace(/^\s*\d+\s*[·—–-]\s*/,'').replace(/^\s*CM\s*[·—–-]\s*/,'').trim();});
 document.querySelectorAll('.hero-kicker,.eyebrow,.breadcrumbs,.project-gateway').forEach(el=>el.remove());
 document.querySelectorAll('.index-art span').forEach(el=>{if(/^\s*\d+\s*$/.test(el.textContent||''))el.remove();});
 document.querySelectorAll('footer div').forEach(el=>{el.textContent=el.textContent.replace(/V—\s*\/\s*\d+/g,'VengrathDM').replace(/\b\d+\s*[·—–-]\s*/g,'').trim();});
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
 const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 nodes.forEach(node=>{const parent=node.parentElement;if(!parent||['SCRIPT','STYLE','NOSCRIPT'].includes(parent.tagName))return;node.nodeValue=node.nodeValue.replace(/\[[^\]]*\]/g,'').replace(/\b\d+\s*[-·—–]\s*(?=[A-Za-zĄĆĘŁŃÓŚŹŻąćęłńóśźż])/g,'').replace(/\s{2,}/g,' ');});
}
function addSkipLink(){const main=document.querySelector('main');if(!main||document.querySelector('.skip-link'))return;if(!main.id)main.id='main';const a=document.createElement('a');a.className='skip-link';a.href='#main';a.textContent='Przejdź do treści';document.body.prepend(a);}
function addSearchTrigger(){if(!siteNav||siteNav.querySelector('[data-global-search]'))return;const b=document.createElement('button');b.type='button';b.className='global-search-trigger';b.dataset.globalSearch='true';b.textContent='SZUKAJ /';siteNav.append(b);initGlobalSearch(b);}
function addMetadata(){const canonical=new URL(location.href);canonical.hash='';if(!document.querySelector('link[rel=canonical]')){const l=document.createElement('link');l.rel='canonical';l.href=canonical.href;document.head.append(l);}const title=document.title||'Vengrath — Atelier',description=document.querySelector('meta[name=description]')?.content||'Vengrath — Mistrz Podziemi, twórca kampanii i budowniczy światów.';for(const[p,c]of[['og:title',title],['og:description',description],['og:url',canonical.href],['og:type','website']])if(!document.querySelector(`meta[property="${p}"]`)){const m=document.createElement('meta');m.setAttribute('property',p);m.content=c;document.head.append(m);}}
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();document.querySelector('[data-global-search]')?.click();}});
document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-2}deg) rotateY(${x*2}deg) translateY(-3px)`;});card.addEventListener('pointerleave',()=>card.style.transform='');});
function initGlobalSearch(trigger){let dialog,input,results,items=[],loaded=false;trigger.addEventListener('click',async()=>{if(!dialog){dialog=buildSearchDialog();input=dialog.querySelector('.global-search__input');results=dialog.querySelector('.global-search__results');}dialog.hidden=false;document.body.classList.add('search-open');input.focus();if(loaded)return;results.innerHTML='<p class="global-search__status">Ładowanie indeksu…</p>';try{items=await loadGlobalSearchIndex();loaded=true;renderResults(input.value);}catch(error){console.error('Global search error:',error);results.innerHTML='<p class="global-search__status">Indeks wyszukiwania jest chwilowo niedostępny.</p>';}});async function loadGlobalSearchIndex(){const baseResponse=await fetch('/search-index.json',{cache:'no-store'});if(!baseResponse.ok)throw new Error(`Search index HTTP ${baseResponse.status}`);const base=await baseResponse.json();const [echtra,heartwell]=await Promise.all([loadLoreManifest('/pages/Projects/echtra-midst-the-sidhe/lore-compendium/articles/index.json','Echtra'),loadLoreManifest('/pages/Projects/ksiazeta-heartwell/lore-compendium/articles/index.json','Heartwell')]);return dedupeSearchItems([...base.map(item=>normalizeSearchItem(item)),...echtra,...heartwell]);}
async function loadLoreManifest(url,source){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${source} manifest HTTP ${response.status}`);const data=await response.json();const categories=Array.isArray(data.categories)?data.categories:[];const articles=Array.isArray(data.articles)?data.articles:[];return articles.filter(article=>article?.file&&article?.title).map(article=>{const category=categories.find(item=>item.id===article.category);const section=category?.title||article.category||'Lore';const base=url.slice(0,url.lastIndexOf('/')+1);return normalizeSearchItem({title:article.title,description:`Wpis w kompendium ${source}.`,type:`${source} · ${section}`,tags:[source,section,article.category||''],url:`${base}?article=${encodeURIComponent(article.file)}`});});}
function normalizeSearchItem(item){return {title:String(item?.title||''),description:String(item?.description||''),type:String(item?.type||'INNE'),tags:Array.isArray(item?.tags)?item.tags.map(String):[],url:String(item?.url||'#')};}
function dedupeSearchItems(list){const seen=new Set();return list.filter(item=>{const key=`${item.title.toLowerCase()}|${item.url}`;if(!item.title||seen.has(key))return false;seen.add(key);return true;});}
function buildSearchDialog(){const overlay=document.createElement('div');overlay.className='global-search';overlay.hidden=true;overlay.innerHTML='<div class="global-search__dialog" role="dialog" aria-modal="true" aria-labelledby="global-search-title"><div class="global-search__top"><div><h2 id="global-search-title">Znajdź w <em>świecie Vengratha.</em></h2></div><button class="global-search__close" type="button" aria-label="Zamknij wyszukiwanie">×</button></div><label class="global-search__field"><span class="sr-only">Szukaj</span><input class="global-search__input" type="search" placeholder="Projekt, kampania, post, lore…" autocomplete="off"></label><div class="global-search__results" aria-live="polite"></div></div>';overlay.querySelector('.global-search__close').addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close();});overlay.querySelector('.global-search__input').addEventListener('input',e=>renderResults(e.target.value));return document.body.appendChild(overlay),overlay;}function renderResults(q){const n=q.trim().toLowerCase(),matches=items.filter(i=>!n||`${i.title} ${i.description} ${i.type} ${i.tags.join(' ')}`.toLowerCase().includes(n)).slice(0,40);if(!matches.length){results.innerHTML='<p class="global-search__status">Brak wyników.</p>';return;}results.replaceChildren(...matches.map(i=>{const a=document.createElement('a');a.className='global-search__result';a.href=new URL(i.url,location.origin).href;a.innerHTML=`<span class="global-search__result-type">${escapeHtml(i.type)}</span><strong>${escapeHtml(i.title)}</strong><span>${escapeHtml(i.description)}</span>`;return a;}));}function close(){dialog.hidden=true;document.body.classList.remove('search-open');}}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
