const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

const steps = [
  { label:"Character", meta:"01" }, { label:"Race", meta:"02" }, { label:"Class", meta:"03" },
  { label:"Abilities", meta:"04" }, { label:"Background", meta:"05" }, { label:"Review", meta:"06" }, { label:"Character Sheet", meta:"07" }
];

function choice(type,value,text,selected) { return `<button class="specimen ${selected?"lit":""}" data-type="${type}" data-value="${escapeHtml(value)}"><span class="specimen-bead"></span><span class="specimen-label">${escapeHtml(text)}</span></button>`; }
function renderLanguageChoice(type, selected, limit, excluded=[]) { return DATA.standardLanguages.filter(l=>!excluded.includes(l)).map(l=>choice(type,l,l,selected.includes(l))).join(""); }
function languageSummary() {
  const race=R.race(), fixed=race?.languages||[], cls=[];
  if(S.className==="Druid") cls.push("Druidic");
  if(S.className==="Rogue") cls.push("Thieves' Cant");
  return [...new Set([...fixed,...(S.racialLanguages||[]),...(S.backgroundLanguages||[]),...cls])];
}
function renderRace() {
  const race=R.race(); const raceChoices=Object.keys(DATA.races).map(r=>choice("race",r,r,S.race===r)).join("");
  if(!race) return `<section><div class="panel-head"><h2>Lineage</h2><p class="panel-sub">Choose your character’s race.</p></div><div class="specimen-rack">${raceChoices}</div></section>`;
  const subraceChoices=Object.keys(race.subs||{}).map(sr=>choice("subrace",sr,sr,S.subrace===sr)).join("");
  const fixedBonuses=Object.entries(race.fixed||{}).map(([a,b])=>`<i>${a} +${b}</i>`).join("");
  const subraceBonuses=Object.entries((race.subs||{})[S.subrace]||{}).map(([a,b])=>`<i>${a} +${b}</i>`).join("");
  const fixedLanguages=race.languages||[], choices=race.languageChoices||0;
  const modes=[["2014","Racial"],["tasha2+1","Tasha +2 / +1"],["tasha1+1+1","Tasha +1 / +1 / +1"]].map(([m,label])=>choice("racialMode",m,label,(m==="2014"&&S.racialMode==="2014")||(m.startsWith("tasha")&&S.racialMode==="tasha"&&S.tashaMode===(m==="tasha2+1"?"2+1":"1+1+1")))).join("");
  return `<section><div class="panel-head"><h2>Lineage</h2><p class="panel-sub">Choose your character’s race and variant.</p></div><div class="specimen-rack">${raceChoices}</div><div class="panel-head"><h2>Variant</h2></div><div class="specimen-rack">${subraceChoices}</div><div class="porthole"><b>Ability Modifiers</b><p class="tags">${S.racialMode==="2014"?(fixedBonuses+subraceBonuses||"None"):"Replaced by Tasha's allocation"}</p><b>Languages</b><p>${fixedLanguages.length?fixedLanguages.map(escapeHtml).join(", "):"None"}</p>${choices?`<label class="field-label">Additional standard language — choose ${choices}</label><div class="specimen-rack">${renderLanguageChoice("racialLanguage",S.racialLanguages||[],choices,fixedLanguages)}</div>`:""}<b>Innate Proficiencies</b><p>${(race.skills||[]).join(", ")||"None"}</p><div class="toggle-row">${modes}</div>${S.racialMode==="tasha"?renderTashaBonuses():""}</div></section>`;
}
function renderTashaBonuses() {
  const values=S.tashaMode==="2+1"?["+2","+1"]:["+1","+1","+1"];
  const tokens=values.map((v,i)=>`<span class="pearl" draggable="true" data-token="${v}" data-i="${i}">${v}</span>`).join("");
  const modes=["2+1","1+1+1"].map(m=>choice("tashaMode",m,m==="2+1"?"Tasha's +2 +1":"Tasha's +1 +1 +1",S.tashaMode===m)).join("");
  const slots=DATA.abilities.map(a=>`<div class="tide-slot ${S.tasha[a]?"is-filled":""}" data-slot="${a}"><span class="tide-slot-name">${a}</span><span class="tide-slot-value">${S.tasha[a]?`+${S.tasha[a]}`:"—"}</span>${S.tasha[a]?`<button class="mini-clear" data-clear-tasha="${a}" title="Clear ${a}">×</button>`:""}</div>`).join("");
  return `<div class="tasha-box"><p class="hint">Assign exactly one bonus to each chosen ability. Tasha's replaces, rather than adds to, the race's normal modifiers.</p><div class="pearl-tray">${tokens}</div><div class="tide-wells">${slots}</div><div class="tasha-actions"><button type="button" data-reset-tasha>Reset Tasha's Bonuses</button></div><p class="allocation-status">${R.tashaComplete()?"Allocation complete.":"Allocation incomplete — assign all bonus pearls."}</p></div>`;
}
function renderClass() {
  const cls=R.cls(); const classChoices=Object.keys(DATA.classes).map(c=>choice("className",c,c,S.className===c)).join("");
  if(!cls) return `<section><div class="panel-head"><h2>Discipline</h2><p class="panel-sub">Choose your character’s class.</p></div><div class="discipline-grid">${classChoices}</div></section>`;
  const subs=cls.subs.map(s=>choice("subclass",s,s,S.subclass===s)).join("");
  const skills=cls.skills.map(s=>choice("classSkill",s,s,S.classSkills.includes(s))).join("");
  const ref=DATA.classReference[S.className]||{};
  const expertiseChoices=[...cls.skills,...(S.className==="Rogue"?["Thieves' tools"]:[])]; const expertise=cls.expertise?`<div class="panel-head"><h2>Expertise <span class="quota">choose up to 2</span></h2></div><div class="specimen-rack">${expertiseChoices.map(s=>choice("expertise",s,s,S.expertise.includes(s))).join("")}</div>`:"";
  return `<section><div class="panel-head"><h2>Discipline</h2><p class="panel-sub">Choose your character’s class and specialization.</p></div><div class="discipline-grid">${classChoices}</div><div class="panel-head"><h2>Specialization</h2></div><div class="specimen-rack">${subs}</div><div class="panel-head"><h2>Class Skills <span class="quota">choose ${cls.n}</span></h2></div><div class="specimen-rack">${skills}</div>${expertise}<div class="porthole reference-panel"><b>Proficiencies</b><p><strong>Armor:</strong> ${ref.armor?.join(", ")||"None"}</p><p><strong>Weapons:</strong> ${ref.weapons?.join(", ")||"None"}</p><p><strong>Tools:</strong> ${ref.tools?.join(", ")||"None"}</p><p><strong>Hit Die:</strong> d${ref.hitDie||"—"}</p><p><strong>Level 1 features:</strong> ${escapeHtml(ref.feature||"—")}</p></div></section>`;
}
function renderAbilities() {
  const tokens=R.scoreArray.map(v=>`<span class="pearl" draggable="true" data-ability="${v}">${v}</span>`).join("");
  const scores=R.scores(), bonuses=R.bonus();
  const gauges=DATA.abilities.map(a=>{const score=scores[a]||0,pct=Math.max(4,Math.min(100,(score/20)*100)),bonus=bonuses[a]||0;return `<div class="gauge ${bonus?"gauge-boosted":""}"><div class="gauge-dial" style="--pct:${pct}"><span class="gauge-score">${score}</span></div><span class="gauge-name">${a}</span><span class="gauge-bonus">${bonus?`+${bonus} racial/Tasha`:"—"}</span><div class="tide-slot" data-ability-slot="${a}"><span class="tide-slot-value">${S.assign[a]||"drop score"}</span>${S.assign[a]?`<button class="mini-clear" data-clear-score="${a}">×</button>`:""}</div></div>`;}).join("");
  return `<section><div class="panel-head"><h2>Ability Scores</h2><p class="panel-sub">Assign 15, 14, 13, 12, 10 and 8 once each. ${S.racialMode==="tasha"?"Tasha's bonuses replace the racial modifiers.":"2014 racial modifiers apply here."}</p></div><div class="pearl-tray">${tokens}</div><div class="gauge-array">${gauges}</div><div class="porthole"><b>Saving Throws</b><p>${R.saves().length?R.saves().map(a=>`${a} ${R.savingThrowModifier(a)}`).join(", "):"Select a class first."}</p></div></section>`;
}
function renderBackground() {
  const choices=DATA.backgrounds.map(b=>choice("background",b,b,S.background===b)).join("");
  if(!S.background) return `<section><div class="panel-head"><h2>Origin</h2><p class="panel-sub">Choose your character’s background.</p></div><div class="specimen-rack">${choices}</div></section>`;
  const rule=DATA.backgroundLanguages[S.background]||{choices:0};
  const skills=S.background==="Custom"?`<label class="field-label">Skill Proficiencies — choose exactly 2</label><div class="specimen-rack">${DATA.skills.map(s=>choice("backgroundSkill",s,s,S.backgroundSkills.includes(s))).join("")}</div>`:`<label class="field-label">Skill Proficiencies</label><div class="specimen-rack">${(DATA.backgroundSkills[S.background]||[]).map(s=>`<span class="specimen lit static"><span class="specimen-bead"></span><span class="specimen-label">${escapeHtml(s)}</span></span>`).join("")}</div>`;
  const ref=DATA.backgroundReference[S.background]||{};
  return `<section><div class="panel-head"><h2>Origin</h2><p class="panel-sub">Choose your character’s background.</p></div><div class="specimen-rack">${choices}</div><div class="porthole"><div class="panel-head"><h2>Background Record</h2></div>${skills}${rule.choices?`<div class="panel-head"><h2>Languages</h2></div><label class="field-label">Choose ${rule.choices} standard language${rule.choices===1?"":"s"}</label><div class="specimen-rack">${renderLanguageChoice("backgroundLanguage",S.backgroundLanguages||[],rule.choices)}</div>`:""}<p><strong>Feature:</strong> ${escapeHtml(ref.feature||"—")}</p><p><strong>Tools:</strong> ${escapeHtml(ref.tools?.join(", ")||"None")}</p><p><strong>Starting equipment:</strong> ${escapeHtml(ref.equipment||"—")}</p><label class="field-label">Notes</label><textarea data-field="notes" placeholder="Additional character notes...">${escapeHtml(S.notes)}</textarea></div></section>`;
}
function renderIdentity() { const align=DATA.alignments.map(a=>choice("alignment",a,a,S.alignment===a)).join(""); return `<section><div class="panel-head"><h2>Character</h2><p class="panel-sub">Basic character identification.</p></div><div class="manifold"><label class="field-block"><span class="field-label">Character Name</span><input data-field="name" placeholder="Unnamed" value="${escapeHtml(S.name)}"></label><label class="field-block"><span class="field-label">Player</span><input data-field="player" placeholder="Player" value="${escapeHtml(S.player)}"></label><label class="field-block"><span class="field-label">Campaign</span><input data-field="campaign" placeholder="Campaign / Chronicle" value="${escapeHtml(S.campaign)}"></label></div><div class="panel-head"><h2>Alignment</h2></div><div class="compass-grid">${align}</div></section>`; }
function renderReview() { const checks=R.validation(); const status=checks.every(x=>x.ok); return `<section><div class="panel-head"><h2>Review</h2><p class="panel-sub">Resolve every required item before the final character sheet.</p></div><div class="porthole review-strip"><span>${escapeHtml(S.name)||"Unnamed"}</span><em>—</em><span>${escapeHtml(S.race)||"?"} / ${escapeHtml(S.subrace)||"?"}</span><em>—</em><span>${escapeHtml(S.className)||"?"} / ${escapeHtml(S.subclass)||"?"}</span><em>—</em><span>${escapeHtml(S.background)||"?"}</span></div><div class="validation-grid">${checks.map(c=>`<div class="validation-item ${c.ok?"ok":"missing"}"><strong>${c.ok?"✓":"✕"}</strong><span>${escapeHtml(c.label)}</span></div>`).join("")}</div><p class="review-status ${status?"ok":"missing"}">${status?"Character is ready for the sheet.":"Complete the missing requirements above."}</p></section>`; }
function renderDossier() {
  const scores=R.scores(), cls=R.cls(), race=R.race(), ref=DATA.classReference[S.className]||{}, bref=DATA.backgroundReference[S.background]||{}, skills=R.proficientSkills(), languages=languageSummary(), expertise=R.expertiseSkills();
  const abilityRows=DATA.abilities.map(a=>`<div class="sheet-stat"><span>${a}</span><strong>${scores[a]||0}</strong><em>${R.modifier(scores[a])}</em></div>`).join("");
  const skillRows=DATA.skills.map(s=>`<span class="sheet-chip ${skills.includes(s)?"is-proficient":""}">${escapeHtml(s)}${skills.includes(s)?` · ${R.skillAbility(s)} ${R.skillModifier(s)}${expertise.includes(s)?" · Expertise":""}`:""}</span>`).join("");
  const saves=(cls?.saves||[]).map(a=>`<span class="sheet-chip is-proficient">${a} ${R.savingThrowModifier(a)}</span>`).join("")||"None";
  const dex=Number(scores.DEX||0), wis=Number(scores.WIS||0), con=Number(scores.CON||0), hitDie=ref.hitDie;
  const baseHP=hitDie?hitDie+Math.floor((con-10)/2):"—";
  const passive=10+Math.floor((wis-10)/2)+(skills.includes("Perception")?2:0)+(expertise.includes("Perception")?2:0);
  const initiative=R.modifier(dex), ac=10+Math.floor((dex-10)/2);
  const validation=R.validation();
  return `<section><div class="panel-head"><h2>Character Sheet</h2><p class="panel-sub">A consolidated 2014-style record derived from every completed choice.</p></div><div class="id-plate"><div class="id-plate-top"><span class="id-plate-tag">CHARACTER RECORD</span><span class="id-plate-tag">LEVEL ${Number(S.level)||1} · PROF ${R.proficiencyBonus()}</span></div><h3>${escapeHtml(S.name)||"Unnamed Character"}</h3><p class="id-plate-role">${escapeHtml(S.race)||"?"} / ${escapeHtml(S.subrace)||"?"} — ${escapeHtml(S.className)||"?"} / ${escapeHtml(S.subclass)||"?"}</p><p class="id-plate-origin">${escapeHtml(S.background)||"?"} · ${escapeHtml(S.alignment)||"Unaligned"}</p></div><div class="combat-strip"><div><small>AC (unarmored)</small><strong>${ac}</strong></div><div><small>Initiative</small><strong>${initiative}</strong></div><div><small>Speed</small><strong>30 ft</strong></div><div><small>HP (level 1)</small><strong>${baseHP}</strong></div><div><small>Hit Die</small><strong>${hitDie?`d${hitDie}`:"—"}</strong></div><div><small>Passive Perception</small><strong>${passive}</strong></div></div><div class="sheet-grid"><div class="sheet-panel"><h3>Ability Scores</h3><div class="sheet-stats">${abilityRows}</div></div><div class="sheet-panel"><h3>Saving Throws</h3><div class="sheet-chips">${saves}</div><p class="sheet-note">Proficiency bonus: ${R.proficiencyBonus()}</p></div><div class="sheet-panel sheet-wide"><h3>Skills</h3><div class="sheet-chips">${skillRows}</div></div><div class="sheet-panel"><h3>Languages</h3><div class="sheet-chips">${languages.map(l=>`<span class="sheet-chip is-language">${escapeHtml(l)}</span>`).join("")||"None"}</div></div><div class="sheet-panel"><h3>Class Proficiencies</h3><p><strong>Armor:</strong> ${escapeHtml(ref.armor?.join(", ")||"None")}</p><p><strong>Weapons:</strong> ${escapeHtml(ref.weapons?.join(", ")||"None")}</p><p><strong>Tools:</strong> ${escapeHtml(ref.tools?.join(", ")||"None")}</p></div><div class="sheet-panel"><h3>Background</h3><p><strong>Feature:</strong> ${escapeHtml(bref.feature||"—")}</p><p><strong>Tools:</strong> ${escapeHtml(bref.tools?.join(", ")||"None")}</p></div><div class="sheet-panel"><h3>Features &amp; Special Rules</h3><p><strong>Class:</strong> ${escapeHtml(ref.feature||"—")}</p><p><strong>Racial mode:</strong> ${S.racialMode==="tasha"?"Tasha's custom ability modifiers":"2014 racial and subrace ability modifiers"}</p><p><strong>Expertise:</strong> ${escapeHtml(expertise.join(", ")||"None")}</p></div><div class="sheet-panel"><h3>Starting Equipment</h3><p>${escapeHtml(bref.equipment||"—")}</p></div>${S.notes?`<div class="sheet-panel sheet-wide"><h3>Notes</h3><p>${escapeHtml(S.notes).replace(/\n/g,"<br>")}</p></div>`:""}</div><div class="sheet-footnote">${validation.every(x=>x.ok)?"Complete character record":"Record contains incomplete selections; return to Review to resolve them."}</div><button class="seal-btn" data-save>Save Character</button></section>`;
}
const renderStep=[renderIdentity,renderRace,renderClass,renderAbilities,renderBackground,renderReview,renderDossier];
window.render=()=>{ const current=renderStep[S.step](); const gauge=steps.map((st,i)=>`<button class="depth-mark ${i===S.step?"current":""} ${i<S.step?"passed":""}" data-step="${i}"><span class="depth-mark-dot"></span><span class="depth-mark-text"><em>${st.meta}</em>${st.label}</span></button>`).join(""); const prev=S.step?'<button data-prev>Previous</button>':""; const next=S.step<6?'<button class="next-btn" data-next>Next</button>':""; $("#app").innerHTML=`<header><div class="brand"><small>Character Builder · D&amp;D 5e</small><h1>Character Builder</h1></div><div class="header-controls"><button data-save>Save</button><button data-load>Load</button><input id="file" type="file" accept=".json" hidden></div></header><div class="hull"><aside class="depth-rail"><div class="depth-rail-line"></div>${gauge}</aside><main>${current}<div class="pager">${prev}${next}</div></main></div>`; };
