const A=[
['heartwell','Heartwell','O mieście','Miasto portowe i przemysłowe, około 150 000 mieszkańców.'],
['technology','Technologia i magia','O mieście','Diesel, tramwaje, kolej, broń prochowa i rzadka magia.'],
['korona','Korona','Dzielnice','Centrum władzy, reprezentacji i życia wyższych warstw.'],
['erozja','Erozja','Dzielnice','Religia, sztuka, rozrywka i relacje.'],
['senatorium','Senatorium','Dzielnice','Szpitale, sanatoria i dzielnica odpoczynku.'],
['apetoria','Apetoria','Dzielnice','Kultura, handel, jedzenie i walka o wpływy.'],
['zabraniec','Zabraniec','Dzielnice','Kapitał, kontrakty, banki i zobowiązania.'],
['wisielcze-wzgorze','Wisielcze Wzgórze','Dzielnice','Prawo, sądy, więzienia i przemysł zbrojeniowy.']
];
const C={
heartwell:['Pierwsza rzecz, którą warto wiedzieć.',`<p>Heartwell jest miastem portowym i przemysłowym. Liczy około <strong>150 000 mieszkańców</strong>, a społeczeństwo jest wyraźnie podzielone klasowo.</p><p>Miasto rozciąga się od Wisielczego Wzgórza na północy po doki nad rzeką na południu. Poza murami znajdują się gospodarstwa, lasy, osady górnicze i port rzeczny.</p><h2>Miasto we Mgle</h2><p>Heartwell i jego okolice zostały pochłonięte przez Mgły. Poza zabudowaniami mgła sięga mniej więcej milę.</p><h2>Władza</h2><p>Formalnie miastem rządzi <strong>siedmiu Książąt</strong> oraz Rada Książąt. Każdy z nich posiada własną dzielnicę i własne interesy.</p><div class="quote">W Heartwell dobrze jest wiedzieć, gdzie jesteś, komu płacisz i kto patrzy.</div>`],
technology:['Co naprawdę działa w Heartwell.',`<p>Heartwell nie jest miastem parowym. Jego charakter technologiczny opiera się przede wszystkim na <strong>silnikach dieslowskich</strong>, sieci tramwajowej, kolei, broni prochowej i fotografii.</p><h2>Elektryczność</h2><p>Elektryczność pozostaje dziedziną eksperymentalną.</p><h2>Magia</h2><p>Magia arkaniczna jest rzadka. Magia boska jest powszechniej rozpoznawana jako dar Jasnego.</p>`],
korona:['Dzielnica Percivala Sinclaira.',`<p>Korona jest centrum władzy i reprezentacji. To tutaj znajdują się <strong>Pałac, Akademia, Ogrody</strong> oraz miejsca związane z życiem wyższych warstw Heartwell.</p><h2>Miejsca</h2><ul><li>Pałac</li><li>Akademia</li><li>Ogrody</li><li>Opera Doriana</li><li>Galeria Harwarda</li><li>Klub Pawia</li></ul>`],
erozja:['Religia, sztuka i pożądanie.',`<p>Erozja jest dzielnicą związaną z <strong>zazdrością i pożądaniem</strong>. Jej życie społeczne skupia się wokół religii, rozrywki, sztuki i relacji.</p><h2>Kościół Jasnego</h2><p>Kościół Jasnego jest oficjalną instytucją religijną Heartwell. Ważnym miejscem jego działalności jest <strong>Katedra św. Bazylego</strong>.</p>`],
senatorium:['Dzielnica odpoczynku.',`<p>Senatorium zbudowano wokół idei odpoczynku. Znajdują się tu <strong>szpitale, sanatoria, domy spokojnej starości, prywatne kliniki i publiczne przytułki</strong>.</p><h2>Atmosfera</h2><p>Jasny piaskowiec, białe kolumny, łagodne linie dachów i ogrody odróżniają je od cięższego charakteru innych części miasta.</p><p>Spokój Senatorium nie zawsze oznacza bezpieczeństwo.</p>`],
apetoria:['Kultura, handel i apetyt.',`<p>Apetoria łączy <strong>kulturę, handel, jedzenie, rozrywkę</strong> i walkę o kontrolę nad rynkami.</p><h2>Dom Handlowy Marchetti</h2><p>Rodzina restauratorów i impresariów, posiadająca sieć restauracji i winiarni.</p><h2>Bracia Ossuary</h2><p>Gracze działający na czarnym rynku.</p><h2>Czerwone Fartuchy</h2><p>Siła ulicy kontrolująca terytorium, rynki i drogi dostaw.</p>`],
zabraniec:['Pieniądz ma tu własną hierarchię.',`<p>Zabraniec jest dzielnicą, w której władza opiera się na <strong>kapitale, długach, kontraktach i zobowiązaniach</strong>.</p><h2>Trzy domy</h2><p><strong>Dom Falcone</strong> buduje władzę przez zobowiązania. <strong>Dom Kurogane</strong> kieruje się surowym kodeksem honorowym. <strong>Dom Reyes</strong> łączy legalną finansjerę z mniej legalnymi interesami.</p>`],
'wisielcze-wzgorze':['Prawo, które nigdy nie śpi.',`<p>Wisielcze Wzgórze jest dzielnicą związaną z <strong>gniewem</strong>. To część miasta podporządkowana sprawiedliwości, procedurze i egzekwowaniu prawa.</p><h2>Prawo</h2><p>Znajdują się tu sądy, więzienia, sale przesłuchań i miejsca wykonywania wyroków.</p><h2>Żelazny Sąd</h2><p>System opiera się na przekonaniu, że rygorystyczna procedura może zapewnić sprawiedliwość.</p><h2>Przemysł</h2><p><strong>Arsenał Ashcroftów</strong> jest niezależną rodziną przemysłową produkującą broń.</p>`]
};
const M={'Korona':['Dzielnica','Centrum władzy i reprezentacji.'],'Erozja':['Dzielnica','Religia, sztuka, rozrywka i relacje.'],'Senatorium':['Dzielnica','Szpitale, sanatoria i odpoczynek.'],'Apetoria':['Dzielnica','Handel, kuchnia, kultura i rynki.'],'Zabraniec':['Dzielnica','Banki, kontrakty, kapitał i zobowiązania.'],'Wisielcze Wzgórze':['Dzielnica','Prawo, sądy, więzienia i przemysł.'],'Pałac':['Miejsce','Najważniejszy symbol Korony.'],'Szpital Psychiatryczny':['Miejsce','Szpital w Senatorium.'],'Apteka pod Czarnym Makiem':['Miejsce','Jedna z lokacji Senatorium.'],'Żelazny Sąd':['Miejsce','Instytucja prawa na Wisielczym Wzgórzu.'],'Arsenał Ashcroftów':['Miejsce','Zakłady rodziny Ashcroftów.'],'Katedra św. Bazylego':['Miejsce','Centrum Kościoła Jasnego.']};
const app=document.querySelector('#app'),nav=document.querySelector('#nav'),search=document.querySelector('#search'),status=document.querySelector('#status');
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function navRender(q=''){q=q.toLowerCase();nav.innerHTML=[...new Set(A.map(x=>x[2]))].map(cat=>{let r=A.filter(x=>x[2]===cat&&(!q||x[1].toLowerCase().includes(q)));return r.length?`<section class="nav-group"><h2>${cat}</h2>${r.map(x=>`<a class="nav-link" href="#article=${x[0]}">${x[1]}</a>`).join('')}</section>`:''}).join('')}
function home(){document.title='Książęta Heartwell — Lore Kompendium';app.innerHTML=`<section class="hero"><div><p class="kicker">Archiwum dla graczy</p><h1>Lore Kompendium</h1><p>Witaj w Heartwell. Wystarczająco dużo, by mieć z czego budować postać, relacje i pomysły — i wystarczająco mało, by tajemnice nadal pozostały tajemnicami.</p></div><div class="stamp">H<small>HEARTWELL · DOSSIER</small></div></section><div class="section-head"><h2>Miasto, które czeka</h2><p>Otwórz artykuł albo zacznij od mapy.</p></div><div class="cards"><a class="card card-link" href="#map"><h3>Mapa Heartwell</h3><p>Interaktywna mapa miasta. Klikaj dzielnice i ważne miejsca.</p><span class="tag">Interaktywne</span></a>${A.slice(0,3).map(x=>`<a class="card card-link" href="#article=${x[0]}"><h3>${x[1]}</h3><p>${x[3]}</p><span class="tag">${x[2]}</span></a>`).join('')}<div class="card full"><h3>Jak czytać kompendium</h3><p>To jest wiedza dla graczy, nie podręcznik Mistrza Gry. Część informacji może być niepełna, stronnicza albo oparta na tym, co mieszkańcy Heartwell sądzą, że wiedzą.</p></div></div>`;status.textContent='Kompendium dla graczy'}
function article(id){let a=A.find(x=>x[0]===id);if(!a)return home();let c=C[id];document.title=a[1]+' — Heartwell';app.innerHTML=`<article class="article"><a class="backlink" href="#">← Kompendium</a><header class="article-head"><p class="eyebrow">${a[2]}</p><h1>${a[1]}</h1><p>${c[0]}</p></header><div class="article-body">${c[1]}</div></article>`;document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.getAttribute('href')===`#article=${id}`));status.textContent=a[1]}
function map(){document.title='Mapa Heartwell — Heartwell';app.innerHTML=`<section class="article"><a class="backlink" href="#">← Kompendium</a><header class="article-head"><p class="eyebrow">Atlas miasta</p><h1>Mapa Heartwell</h1><p>Kliknij punkt, aby otworzyć notatkę.</p></header><div class="map-layout"><div class="map-frame"><img src="./heartwell-map.jpg" alt="Mapa miasta Heartwell"><button class="hotspot district" style="left:53%;top:37%" data-m="Korona"></button><button class="hotspot district" style="left:76%;top:45%" data-m="Erozja"></button><button class="hotspot district" style="left:38%;top:38%" data-m="Senatorium"></button><button class="hotspot district" style="left:72%;top:66%" data-m="Apetoria"></button><button class="hotspot district" style="left:36%;top:69%" data-m="Zabraniec"></button><button class="hotspot district" style="left:25%;top:57%" data-m="Wisielcze Wzgórze"></button><button class="hotspot" style="left:54%;top:29%" data-m="Pałac"></button><button class="hotspot" style="left:40%;top:43%" data-m="Szpital Psychiatryczny"></button><button class="hotspot" style="left:45%;top:55%" data-m="Apteka pod Czarnym Makiem"></button><button class="hotspot" style="left:24%;top:65%" data-m="Żelazny Sąd"></button><button class="hotspot" style="left:34%;top:75%" data-m="Arsenał Ashcroftów"></button><button class="hotspot" style="left:75%;top:49%" data-m="Katedra św. Bazylego"></button></div><aside><div class="card"><h3 id="mt">Heartwell</h3><p id="mx">Niebieskie punkty oznaczają dzielnice. Czerwone — ważne miejsca.</p><div class="legend"><span><i class="blue"></i>Dzielnica</span><span><i></i>Lokacja</span></div></div><div class="card"><h3>Atlas miasta</h3><p>Mapa służy do orientacji i planowania. Nie jest pełnym spisem budynków Heartwell.</p></div></aside></div></section>`;document.querySelectorAll('.hotspot').forEach(h=>h.onclick=()=>{document.querySelectorAll('.hotspot').forEach(x=>x.classList.remove('active'));h.classList.add('active');let d=M[h.dataset.m]||['Lokacja','Brak notatki.'];document.querySelector('#mt').textContent=h.dataset.m;document.querySelector('#mx').textContent=d[0]+'. '+d[1]});status.textContent='Mapa Heartwell'}
function route(){let h=decodeURIComponent(location.hash.slice(1));if(h==='map')return map();if(h.startsWith('article='))return article(h.slice(8));home()}
search.oninput=e=>navRender(e.target.value);window.onhashchange=route;navRender();route();
