(function(){
"use strict";
var API="https://api.github.com/repos/vengrathdm/vengrathdm.github.io/contents/SecretProjects/Echtra/articles";
var el={rail:document.getElementById("rail"),index:document.getElementById("index"),head:document.getElementById("indexHead"),sheet:document.getElementById("sheet"),search:document.getElementById("q"),gm:document.getElementById("gmToggle")};
var state={section:null,entry:null,query:""},CATALOG=[],ARTICLES=Object.create(null),SECTIONS=[];
function h(tag,cls,html){var n=document.createElement(tag);if(cls)n.className=cls;if(html!=null)n.innerHTML=html;return n}
function store(k,v){try{if(v===undefined)return localStorage.getItem(k);localStorage.setItem(k,v)}catch(e){}return null}
function findEntry(s,e){var r=CATALOG.find(function(x){return x.section===s&&x.entry===e});return r?ARTICLES[r.key]:null}
function listKeys(c){c.addEventListener("keydown",function(e){var keys=["ArrowDown","ArrowUp","Home","End"];if(keys.indexOf(e.key)<0)return;var a=[].slice.call(c.querySelectorAll("button")),i=a.indexOf(document.activeElement);if(i<0||!a.length)return;e.preventDefault();var n=i;if(e.key==="ArrowDown")n=(i+1)%a.length;if(e.key==="ArrowUp")n=(i-1+a.length)%a.length;if(e.key==="Home")n=0;if(e.key==="End")n=a.length-1;a[n].focus()})}
function makeArticle(url){return fetch(url,{cache:"no-cache"}).then(function(r){if(!r.ok)throw Error("Article fetch failed: "+r.status);return r.text()}).then(function(src){var d=new DOMParser().parseFromString(src,"text/html"),root=d.querySelector("article.article-source");if(!root)throw Error("Missing article-source: "+url);return{key:root.dataset.section+"/"+root.dataset.id,section:root.dataset.section,entry:root.dataset.id,sectionLabel:root.dataset.sectionLabel||root.dataset.section,sectionHead:root.dataset.sectionHead||root.dataset.sectionLabel||root.dataset.section,name:root.dataset.name||root.querySelector(".entry__title").textContent,kicker:root.dataset.kicker||"",sub:root.dataset.sub||"",content:root.querySelector(".article-content")}})}
function rebuild(){CATALOG=Object.keys(ARTICLES).map(function(k){var a=ARTICLES[k];return{key:k,section:a.section,sectionLabel:a.sectionLabel,entry:a.entry,name:a.name,kicker:a.kicker,haystack:(a.name+" "+a.kicker+" "+a.sub+" "+a.content.textContent).toLocaleLowerCase("en")}});CATALOG.sort(function(a,b){return a.name.localeCompare(b.name)});var m=Object.create(null);CATALOG.forEach(function(a){if(!m[a.section])m[a.section]={id:a.section,label:a.sectionLabel,head:ARTICLES[a.key].sectionHead,entries:[]};m[a.section].entries.push(a)});SECTIONS=Object.keys(m).map(function(k){return m[k]});var order={campaign:1,chapters:2,appendices:3};SECTIONS.sort(function(a,b){return(order[a.id]||9)-(order[b.id]||9)});document.querySelector('[data-count="entries"]').textContent=CATALOG.length;document.querySelector('[data-count="chapters"]').textContent=CATALOG.filter(function(x){return x.section==="chapters"}).length;document.querySelector('[data-count="appendices"]').textContent=CATALOG.filter(function(x){return x.section==="appendices"}).length}
function renderRail(){el.rail.innerHTML="";SECTIONS.forEach(function(s){var li=h("li"),b=h("button","rail__btn",s.label+"<span class='rail__count'>"+s.entries.length+"</span>");b.type="button";b.dataset.section=s.id;b.onclick=function(){state.query="";el.search.value="";go(s.id,s.entries[0].entry)};li.appendChild(b);el.rail.appendChild(li)});listKeys(el.rail)}
function rows(){return CATALOG.filter(function(r){return r.section===state.section})}
function search(q){var n=q.toLocaleLowerCase("en").trim();return CATALOG.filter(function(r){return r.haystack.indexOf(n)!==-1}).slice(0,80)}
function renderIndex(){el.index.innerHTML="";var r=state.query?search(state.query):rows();if(!r.length){el.index.appendChild(h("li","index__empty","Nothing matches “"+state.query+"”. Try a place, character, faction, creature or chapter name."));return}r.forEach(function(x){var li=h("li"),label=x.name;if(state.query)label+="<small>"+x.sectionLabel+" · "+x.kicker+"</small>";var b=h("button","index__btn",label);b.type="button";b.dataset.entry=x.entry;if(x.section===state.section&&x.entry===state.entry)b.setAttribute("aria-current","true");b.onclick=function(){go(x.section,x.entry)};li.appendChild(b);el.index.appendChild(li)});listKeys(el.index)}
function markRail(){[].forEach.call(el.rail.querySelectorAll(".rail__btn"),function(b){if(b.dataset.section===state.section&&!state.query)b.setAttribute("aria-current","true");else b.removeAttribute("aria-current")})}
function wireXrefs(){[].forEach.call(el.sheet.querySelectorAll("a.xref"),function(a){a.onclick=function(e){var m=(a.getAttribute("href")||"").match(/^#\/(.+)\/(.+)$/);if(!m)return;e.preventDefault();go(m[1],m[2])}})}
function go(s,e,skip){var a=findEntry(s,e);if(!a){if(!CATALOG.length)return;a=ARTICLES[CATALOG[0].key];s=CATALOG[0].section;e=CATALOG[0].entry}state.section=s;state.entry=e;el.sheet.innerHTML="";el.sheet.appendChild(a.content.cloneNode(true));document.title=a.name+" — Echtra midst the Sidhe";el.head.textContent=a.sectionHead;wireXrefs();renderIndex();markRail();if(!skip)history.replaceState(null,"","#/"+s+"/"+e);el.sheet.scrollIntoView({block:"start"})}
function fromHash(){var m=location.hash.match(/^#\/(.+?)\/(.+)$/);if(m&&findEntry(m[1],m[2]))go(m[1],m[2],true);else if(CATALOG.length)go(CATALOG[0].section,CATALOG[0].entry,true)}
function setGm(on){el.gm.setAttribute("aria-pressed",String(on));document.documentElement.classList.toggle("gm-off",!on);store("echtra-gm",on?"1":"0")}
function load(){fetch(API,{cache:"no-cache"}).then(function(r){if(!r.ok)throw Error("GitHub API: "+r.status);return r.json()}).then(function(items){return Promise.all(items.filter(function(i){return i.type==="file"&&/\.html$/i.test(i.name)}).map(function(i){return makeArticle(i.download_url)}))}).then(function(as){as.forEach(function(a){ARTICLES[a.key]=a});rebuild();renderRail();fromHash();setGm(store("echtra-gm")!=="0")}).catch(function(err){el.index.innerHTML="";el.sheet.innerHTML="<p class='entry__lead'>The Echtra articles could not be loaded.</p><p>"+err.message+"</p><p>Refresh GitHub Pages after the repository has updated.</p>"})}
el.search.oninput=function(){state.query=el.search.value;renderIndex();markRail()};
el.search.onkeydown=function(e){if(e.key==="Escape"){el.search.value="";state.query="";renderIndex();markRail()}if(e.key==="Enter"){var b=el.index.querySelector("button");if(b)b.click()}};
document.addEventListener("keydown",function(e){if(e.key==="/"&&document.activeElement!==el.search){e.preventDefault();el.search.focus()}if(e.key==="Escape"&&document.activeElement===el.search){el.search.value="";state.query="";renderIndex();markRail();el.search.blur()}});
el.gm.onclick=function(){setGm(el.gm.getAttribute("aria-pressed")!=="true")};
window.addEventListener("hashchange",fromHash);load();
})();