window.S = {
  schemaVersion: 3,
  step: 0,
  name: "",
  player: "",
  campaign: "",
  alignment: "",
  level: 1,
  race: "",
  subrace: "",
  racialMode: "2014",
  tashaMode: "2+1",
  tasha: {},
  racialSkills: [],
  racialLanguages: [],
  className: "",
  subclass: "",
  classSkills: [],
  expertise: [],
  background: "",
  backgroundSkills: [],
  backgroundLanguages: [],
  assign: {},
  notes: ""
};
