export const categories = [
  { id: 'all', label: 'Wszystko' }, { id: 'irgaelia', label: 'Irgaela' }, { id: 'divinities', label: 'Bóstwa' }, { id: 'sidhe', label: 'Sidhe i Inny Świat' }, { id: 'fomorian', label: 'Fomorianie' }, { id: 'wyrms', label: 'Wielkie Wyrmy' }, { id: 'magical-beings', label: 'Istoty magiczne' }, { id: 'magic-items', label: 'MAGICZNE PRZEDMIOTY' }, { id: 'magic-materials', label: 'MAGICZNE MATERIAŁY' }
];
const article = (id,title,category,eyebrow,summary,body,tags=[]) => ({id,title,category,eyebrow,summary,body,tags});
export const entries = [
article('irgaela','Irgaela','irgaelia','ŚWIAT · KRAINA ŚMIERTELNIKÓW','Kraina śmiertelników, do której przybyli bogowie z Ziem Zachodu.','Irgaela była początkowo zamieszkana przez śmiertelników i rządzona przez cztery pierwotne Wyrmy. Bogowie przybyli tu po wojnie na Ziemiach Zachodu i zwyciężyli w Wojnie Mocy i Skrzydeł.'),
article('people-and-tribes','Ludzie i Plemiona','irgaelia','IRGAELA · LUDY','Plemiona Tuath tworzą wspólnotę śmiertelników.','Plemiona Irgaeli zachowują własne tradycje, ziemie i więzi z miejscami świętymi.'),
article('places-and-regions','Miejsca i Regiony','irgaelia','IRGAELA · GEOGRAFIA','Najważniejsze krainy, osady i miejsca Irgaeli.','Do ważnych miejsc należą Comairle, Cúilfeorna, Trá Fuara, Ravenpass i Raven’s Perch.'),
article('places-of-power','Miejsca Mocy i Święte Miejsca','irgaelia','IRGAELA · SACRUM','Święte miejsca, gdzie świat śmiertelników styka się z boską potęgą.','Szczególne znaczenie mają Cztery Święte Drzewa oraz świątynie i kaplice poświęcone bóstwom.'),
article('culture-traditions','Kultura i Tradycje','irgaelia','IRGAELA · ZWYCZAJE','Obyczaje, święta i wierzenia mieszkańców Irgaeli.','Kultura Irgaeli wiąże się z porami roku, pamięcią przodków, tradycjami druidycznymi i cienką granicą między światami.'),
article('history-of-gods','Historia Bogów','divinities','BÓSTWA · HISTORIA','Historia bogów od Ziem Zachodu do Irgaeli.','Bogowie i Fomorianie prowadzili wojnę na Ziemiach Zachodu. Bogowie odpłynęli do Irgaeli, gdzie pokonali cztery pierwotne Wyrmy.'),
article('dagda','Dagda','divinities','BÓSTWO · MĄDROŚĆ I ŻYCIE','Potężna postać ojcowska związana z życiem i mądrością.','Dagda wraz z Danu pokonał Féileacánacha, ciskając na niego górę, która stała się Kościaną Górą.'),
article('danu','Danu','divinities','BÓSTWO · BOSKA MATKA','Boska Matka związana z ziemią i stworzeniem.','Danu jest jedną z najważniejszych boskich postaci Irgaeli i uczestniczyła w pokonaniu Féileacánacha.'),
article('brigid','Brigid','divinities','BÓSTWO · OGNISKO INSPIRACJI','Bogini ognia, twórczości, rzemiosła i uzdrawiania.','Brigid jest patronką rzemieślników, poetów i uzdrowicieli.'),
article('lugh','Lugh','divinities','BÓSTWO · ŚWIATŁO I MISTRZOSTWO','Bóg słońca, sztuki, wojny i rzemiosła.','Lugh, Długoręki, ucieleśnia mistrzostwo, precyzję, sztukę i siłę.'),
article('cernunnos','Cernunnos','divinities','BÓSTWO · DZIKOŚĆ','Bóg natury, zwierząt, wolności i przemiany.','Cernunnos reprezentuje pierwotne siły natury, zwierzęta i instynkt.'),
article('morrigan','Morrigan','divinities','BÓSTWO · LOS I WOJNA','Widmowa Królowa związana z losem, wojną i przepowiednią.','Morrigan działa poprzez los, konflikty i przepowiednie.'),
article('manannan','Manannán','divinities','BÓSTWO · MORZE','Bóg morza, który pomógł uwięzić Caoránacha.','Manannán wraz z Cailleach i innymi bogami uwięził Caoránacha łańcuchami z żywej wody.'),
article('cailleach','Cailleach','divinities','BÓSTWO · ZIMA','Bogini zimy i lodu.','Cailleach wraz z Manannánem pomogła uwięzić Caoránacha w Krainach Zawsze Zimy.'),
article('otherworld','Inny Świat','sidhe','SIDHE · INNY ŚWIAT','Rzeczywistość poza światem śmiertelników.','W Innym Świecie przysięgi, język, przysługi i pakty mają szczególne znaczenie.'),
article('sidhe','Sidhe','sidhe','INNY ŚWIAT · ISTOTY','Tajemniczy lud Innego Świata.','Sidhe kierują się logiką Innego Świata, w której słowa i obietnice mogą być prawem.'),
article('seelie-unseelie','Seelie i Unseelie','sidhe','SIDHE · DWIE TRADYCJE','Dwie wielkie strony dworskiego porządku Sidhe.','Seelie i Unseelie reprezentują odmienne nurty kultury Sidhe; nie są prostym podziałem dobra i zła.'),
article('court-winter','Dwór Zimy','sidhe','SIDHE · DWÓR','Dwór chłodu, ciszy i surowego piękna.','Dwór Zimy jest związany z porządkiem i bezruchem zimnej pory roku.'),
article('court-spring','Dwór Wiosny','sidhe','SIDHE · DWÓR','Dwór odrodzenia i budzącego się życia.','Dwór Wiosny reprezentuje odrodzenie, ruch i młode życie.'),
article('court-summer','Dwór Lata','sidhe','SIDHE · DWÓR','Dwór światła, obfitości i pełni życia.','Dwór Lata reprezentuje wzrost, obfitość i szczyt sił natury.'),
article('court-autumn','Dwór Jesieni','sidhe','SIDHE · DWÓR','Dwór zbiorów, zmierzchu i przemiany.','Dwór Jesieni reprezentuje zbiory, dojrzałość i przejście ku zimie.'),
article('fomorian-history','Historia Fomorian','fomorian','FOMORIANIE · HISTORIA','Dzieje Fomorian z odległych Ziem Zachodu.','Fomorianie i bogowie prowadzili na Ziemiach Zachodu długą wojnę. Bogowie ostatecznie odpłynęli do Irgaeli.'),
article('balor','Balor Złego Oka','fomorian','FOMORIANIE · WŁADCA','Potężny władca Fomorian o fiendycznej, czerwonoookiej głowie.','Przepowiednia mówi, że ktoś z krwi i oka Balora ma doprowadzić do jego śmierci.'),
article('osmandias','Osmandias Stormeye','fomorian','FOMORIANIE · KAPITAN CZARNEJ FLOTY','Syn Balora i kapitan Czarnej Floty.','Osmandias jest jedynym żyjącym dzieckiem Balora i dobrowolnym wygnańcem. Dowodzi Czarną Arką, nad którą stale unosi się magiczna burza.'),
article('ceithleen','Ceithleen o Krzywych Zębach','fomorian','FOMORIANIE · BOGINI','Zła bogini zmiany losu, przemocy, ironii i śmiechu.','Ceithleen włada zmianą losu, niepokojącymi snami, zmianą, przemocą, ironią i śmiechem.'),
article('primordial-wyrms','Pierwotne Wyrmy Irgaeli','wyrms','WIELKIE WYRMY · POCZĄTKI','Cztery pradawne Wyrmy, które władały Irgaelą.','Caoránach, Cruimheach, Féileacánach i Cnagach byli pierwotnymi władcami Irgaeli.'),
article('caoranach','Caoránach, Mroźny Wyrm','wyrms','WIELKIE WYRMY · ZIMA','Pradawny Wyrm uwięziony w Krainach Zawsze Zimy.','Manannán i Cailleach uwięzili go łańcuchami z żywej wody i strącili za zamarznięte morze.'),
article('cruimheach','Cruimheach, Magmowy Wyrm','wyrms','WIELKIE WYRMY · MAGMA','Wyrm magmy schwytany przez Fomorian.','Po decydującej bitwie został schwytany przez Fomorian i związany z Tronem Balora.'),
article('feileacanach','Féileacánach, Kryształowy Wyrm','wyrms','WIELKIE WYRMY · KRYSZTAŁ','Wyrm pokonany pod górą, która stała się Kościaną Górą.','Dagda i Danu ciskali na niego górę. Na Kościanej Górze żyje plemię Dragonborn próbujące przeprowadzić próbę związaną z esencją Wyrma.'),
article('cnagach','Cnagach, Piorunowy Wyrm','wyrms','WIELKIE WYRMY · BURZA','Wyrm, który uciekł i pozostaje w ukryciu.','Cnagach uniknął losu pozostałych Wyrmów i od czasów Wojny Mocy i Skrzydeł pozostaje w ukryciu.'),
article('tressym','Tressym','magical-beings','ISTOTY MAGICZNE · WODA','Może narodzić się, gdy spadająca gwiazda wpada do wody.','Upadek gwiazdy do zbiornika wodnego może dać początek Tressymowi.'),
article('hags','Hagi','magical-beings','ISTOTY MAGICZNE','Istoty związane z magią, klątwami i paktami.','Hagi często posługują się magią, która ma swoją cenę i wypacza naturalny porządek.'),
article('demons','Demony','magical-beings','ISTOTY MAGICZNE · FIENDY','Fiendy podatne na działanie Orichalcum.','Orichalcum jest metalem, który rani Fiendy, w tym demony.'),
article('shadows','Cienie','magical-beings','ISTOTY MAGICZNE','Nieuchwytne istoty związane z cieniem.','Cienie należą do dziwnych istot spotykanych na granicy znanego świata.'),
article('phoenixes','Feniksy','magical-beings','ISTOTY MAGICZNE · OGIEŃ','Feniks może narodzić się w płonącym ogniu po upadku gwiazdy.','Gdy spadająca gwiazda spadnie w płonący ogień, rodzi się Feniks.'),
article('silver-hand','Srebrna Dłoń Nuady','magic-items','MAGICZNE PRZEDMIOTY','Legendarny artefakt związany z Nuadą.','Srebrna Dłoń Nuady należy do najważniejszych relikwii boskiej epoki.'),
article('auric-edge','Auric Edge','magic-items','MAGICZNE PRZEDMIOTY','Boska broń o złotym blasku.','Auric Edge jest jedną z legendarnych broni epoki bogów.'),
article('claio-solais','Claíomh Solais','magic-items','MAGICZNE PRZEDMIOTY','Legendarny Miecz Światła.','Claíomh Solais jest jedną z boskich broni tradycji Irgaeli.'),
article('fragarach','Fragarach, Odwetnik','magic-items','MAGICZNE PRZEDMIOTY','Słynna broń związana z odwetem.','Fragarach jest jedną z legendarnych boskich broni.'),
article('eight-divine-weapons','Osiem Boskich Broni','magic-items','MAGICZNE PRZEDMIOTY · RELIKWIE','Zbiór ośmiu legendarnych broni epoki bogów.','Osiem Boskich Broni stanowi osobny zbiór relikwii.'),
article('cold-iron','Zimne Żelazo','magic-materials','MAGICZNE MATERIAŁY','Metal, który rani istoty Fey.','Zimne Żelazo jest szczególnie niebezpieczne dla Fey.'),
article('orichalcum','Orichalcum','magic-materials','MAGICZNE MATERIAŁY','Złoty metal o czerwonym odcieniu, który rani Fiendy.','Orichalcum ma złoty kolor z czerwonym odcieniem i rani Fiendy.'),
article('starmetal','Starmetal','magic-materials','MAGICZNE MATERIAŁY','Metal pozostający po upadku gwiazdy, który rani Aberracje i Monstrosities.','Gdy spadająca gwiazda uderza w ziemię, pozostają fragmenty Starmetalu. Materiał ten rani Aberracje i Monstrosities.')
];
